#!/bin/bash
# AliView Linux Installer
# Compatible with: Ubuntu 20.04+, Debian 11+, Fedora 38+, Arch Linux, openSUSE Leap/Tumbleweed
# (the bundled JRE sets the glibc floor; build the app-image with a low-glibc
#  JDK such as Temurin to keep this compatibility range wide)

set -euo pipefail

# Force a sane umask. If the .run is launched under a restrictive umask (e.g.
# 077, common for root on hardened systems), the system caches regenerated by
# gtk-update-icon-cache / update-mime-database / update-desktop-database inherit
# it and become root-only (0600). Normal users then cannot read the icon/MIME
# databases, which breaks icon loading desktop-wide — on XFCE this crashes
# xfce4-panel (libwnck default-icon assertion). 022 keeps them world-readable.
umask 022

# --- Configuration ---
APP_NAME="aliview"
APP_BINARY="AliView"
INSTALL_DIR="/opt/$APP_NAME"
INSTALL_DIR_EXPECTED="/opt/aliview"   # sanity-check anchor — never changes
BIN_LINK="/usr/local/bin/$APP_NAME"
ICON_SRC="splash_128x128.png"
ICON_DEST_NAME="aliview"
ICON_DEST="/usr/share/icons/hicolor/128x128/apps/${ICON_DEST_NAME}.png"
DESKTOP_FILE="/usr/share/applications/aliview.desktop"
MIME_XML_DEST="/usr/share/mime/packages/aliview.xml"
APP_VERSION="1.0"
INSTALL_MARKER="$INSTALL_DIR/.installing"
LOG_FILE="$INSTALL_DIR/install.log"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# --- Sanity check: guard against a misconfigured INSTALL_DIR variable
#     before we ever touch the filesystem with rm -rf ---
if [ "$INSTALL_DIR" != "$INSTALL_DIR_EXPECTED" ]; then
    echo -e "${RED}Error:${NC} INSTALL_DIR sanity check failed."
    echo "  Expected: $INSTALL_DIR_EXPECTED"
    echo "  Got:      $INSTALL_DIR"
    echo "Do not modify INSTALL_DIR without also updating INSTALL_DIR_EXPECTED."
    exit 1
fi

# --- Trap: only clean up if our in-progress marker exists,
#     AND the path still matches what we expect ---
cleanup_on_error() {
    local lineno="${1:-unknown}"
    echo ""
    echo -e "${RED}ERROR: Installation failed at line $lineno.${NC}"
    if [ -f "$INSTALL_MARKER" ] && [ "$INSTALL_DIR" = "$INSTALL_DIR_EXPECTED" ]; then
        echo "-> Cleaning up incomplete install at $INSTALL_DIR..."
        rm -rf "$INSTALL_DIR"
    else
        echo "-> Skipping cleanup (marker not found or path mismatch)."
    fi
    exit 1
}
trap 'cleanup_on_error $LINENO' ERR

echo -e "${BLUE}=== AliView Linux Installer ===${NC}"
echo ""

# 1. Root check
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error:${NC} Please run as root: sudo ./aliview.install.run"
    exit 1
fi

# 2. Verify the launcher is present. This script runs from the extracted package
#    root, and a jpackage app-image always places the launcher at ./bin/<AppName>.
#    If it is missing or not executable, the package is corrupt — fail fast.
if [ ! -f "./bin/$APP_BINARY" ] || [ ! -x "./bin/$APP_BINARY" ]; then
    echo -e "${RED}Error:${NC} Expected launcher ./bin/$APP_BINARY is missing or not executable."
    echo "The package appears to be corrupt."
    exit 1
fi

# 3. Detect distro family
DISTRO="unknown"
if [ -f /etc/os-release ]; then
    # shellcheck source=/dev/null
    . /etc/os-release
    case "${ID_LIKE:-} ${ID:-}" in
        *fedora*|*rhel*|*centos*)  DISTRO="rpm-fedora" ;;
        *suse*)                    DISTRO="rpm-suse"   ;;
        *arch*)                    DISTRO="arch"       ;;
        *debian*|*ubuntu*)         DISTRO="debian"     ;;
    esac
fi
echo "-> Detected distro family: $DISTRO"

# 4. Detect SELinux state
SELINUX_ACTIVE=false
if command -v getenforce &> /dev/null; then
    SE_STATE=$(getenforce 2>/dev/null || echo "Disabled")
    if [ "$SE_STATE" = "Enforcing" ] || [ "$SE_STATE" = "Permissive" ]; then
        SELINUX_ACTIVE=true
        echo "-> SELinux detected: $SE_STATE"
    fi
fi

# 5. Refuse to run over a prior .deb-installed AliView (version 1.31 shipped as
#    a .deb). That package installed to the SAME /opt/aliview and is tracked by
#    dpkg, so overwriting it would leave dpkg inconsistent — and a later
#    `apt remove aliview` would then delete THIS install. We deliberately do not
#    touch the package manager ourselves; instead we ask the user to remove it,
#    keeping them in control of their system's package state.
# Match only the actually-installed state. `apt remove` (without purge) leaves
# the package in "config-files" state, which `dpkg -s` still reports as known —
# so we check the Status field explicitly and treat config-files/deinstalled
# (files already gone) as safe to proceed.
if command -v dpkg &> /dev/null && \
   dpkg-query -W -f='${Status}' aliview 2>/dev/null | grep -q 'install ok installed'; then
    echo -e "${RED}Error:${NC} AliView is currently installed via your package manager (.deb)."
    echo "It occupies the same location ($INSTALL_DIR) this installer uses."
    echo "Please remove it first, then run this installer again:"
    echo ""
    echo "    sudo apt remove aliview"
    echo ""
    echo "(on non-apt systems: sudo dpkg -r aliview)"
    exit 1
fi

# 5a. Cleanup old /opt version (from a previous .run install)
if [ -d "$INSTALL_DIR" ]; then
    echo "-> Removing existing version at $INSTALL_DIR..."
    rm -rf "$INSTALL_DIR"
fi

# 5b. Remove artifacts from the OLD (pre-/opt) install layout, if present.
#     The old (2018) installer used /usr/bin, /usr/share/aliview and a
#     capitalized AliView.desktop — none of which collide with the new paths,
#     so they would otherwise survive as a stale launcher and a duplicate menu
#     entry. Every removal is guarded by a content fingerprint so we only ever
#     delete the genuine 2018 artifacts and never clobber another AliView
#     install (e.g. a distro package) that happens to use the same paths.
echo "-> Checking for a previous (legacy) AliView installation..."

# True only for the 2018 /usr/bin/aliview wrapper: a regular file (not a
# symlink) carrying both of its signature strings.
is_legacy_aliview_wrapper() {
    local f="$1"
    [ -f "$f" ] && [ ! -L "$f" ] || return 1
    grep -q 'Wrapper script version 29 Jan 2018' "$f" 2>/dev/null || return 1
    grep -q 'defprogdir="/usr/share/aliview"' "$f" 2>/dev/null || return 1
    return 0
}

# True only for the 2018 AliView.desktop: its Exec= is the bare command
# "aliview" (the modern entries use an absolute path).
is_legacy_aliview_desktop() {
    local f="$1"
    [ -f "$f" ] || return 1
    grep -q '^Exec=aliview' "$f" 2>/dev/null
}

# Old launcher (new one is a symlink in /usr/local/bin)
if is_legacy_aliview_wrapper /usr/bin/aliview; then
    echo "   Removing legacy launcher /usr/bin/aliview"
    rm -f /usr/bin/aliview
fi

# Old data dir — only if it holds the legacy jar
if [ -d /usr/share/aliview ] && [ -f /usr/share/aliview/aliview.jar ]; then
    echo "   Removing legacy data dir /usr/share/aliview"
    rm -rf /usr/share/aliview
fi

# Old system desktop entry (capitalized -> would show as a duplicate menu item)
if is_legacy_aliview_desktop /usr/share/applications/AliView.desktop; then
    echo "   Removing legacy desktop entry /usr/share/applications/AliView.desktop"
    rm -f /usr/share/applications/AliView.desktop
fi

# Old per-user desktop entry, in the invoking user's home (not root's)
if [ -n "${SUDO_USER:-}" ]; then
    # Tolerate an unresolvable user: this is best-effort cleanup and must never
    # abort the install (a bare failing assignment would, under set -e).
    USER_HOME="$(getent passwd "$SUDO_USER" 2>/dev/null | cut -d: -f6)" || USER_HOME=""
    USER_DESKTOP="$USER_HOME/.local/share/applications/AliView.desktop"
    if [ -n "$USER_HOME" ] && is_legacy_aliview_desktop "$USER_DESKTOP"; then
        echo "   Removing legacy menu entry for user $SUDO_USER"
        rm -f "$USER_DESKTOP"
    fi
fi

# 6. Create install dir and drop in-progress marker so the trap
#    knows it is safe to clean up on failure from this point on
mkdir -p "$INSTALL_DIR"
touch "$INSTALL_MARKER"

# Start log now that the dir exists
echo "AliView install log — $(date)" > "$LOG_FILE"
echo "Distro: $DISTRO | SELinux: $SELINUX_ACTIVE" >> "$LOG_FILE"

# 7. Deploy files: copy every top-level entry from the extracted package except
#    this installer script. cp -a is sufficient — step 8 resets ownership and
#    permissions afterward, so preserving attributes here doesn't matter.
echo -e "-> Installing files to ${GREEN}$INSTALL_DIR${NC}..."
find . -maxdepth 1 -mindepth 1 ! -name "install.sh" -exec cp -a {} "$INSTALL_DIR/" \;

# Record installed version
echo "$APP_VERSION" > "$INSTALL_DIR/.version"

# 8. Fix ownership and permissions
#    cp -a preserves source ownership, which can be a normal user from the build
#    machine. Reset everything to root:root and make the tree world-readable so
#    normal users can actually launch the app.
echo "-> Setting ownership and permissions..."
chown -R root:root "$INSTALL_DIR"
find "$INSTALL_DIR" -type d -exec chmod 755 {} \;
find "$INSTALL_DIR" -type f -perm /111 -exec chmod 755 {} \;
find "$INSTALL_DIR" -type f ! -perm /111 -exec chmod 644 {} \;

# 9. SELinux context fix
if [ "$SELINUX_ACTIVE" = true ]; then
    if command -v restorecon &> /dev/null; then
        echo "-> Applying SELinux file contexts (restorecon)..." | tee -a "$LOG_FILE"
        restorecon -R "$INSTALL_DIR/" 2>/dev/null || \
            echo -e "   ${YELLOW}Warning:${NC} restorecon failed. If AliView won't launch, run: sudo restorecon -R $INSTALL_DIR"
    elif command -v chcon &> /dev/null; then
        echo "-> Applying SELinux file contexts (chcon fallback)..." | tee -a "$LOG_FILE"
        chcon -R -t bin_t "$INSTALL_DIR/bin/" 2>/dev/null || true
        chcon -R -t lib_t "$INSTALL_DIR/lib/" 2>/dev/null || true
    else
        echo -e "   ${YELLOW}Warning:${NC} SELinux active but no labelling tool found." | tee -a "$LOG_FILE"
        echo "   If AliView won't launch, try: sudo restorecon -R $INSTALL_DIR"
    fi
fi

# 10. Create launcher symlink
echo "-> Creating symbolic link at $BIN_LINK..."
mkdir -p "$(dirname "$BIN_LINK")"
ln -sf "$INSTALL_DIR/bin/$APP_BINARY" "$BIN_LINK"

# 11. Install icon via hicolor theme
#     Named icon (not hardcoded path) = correct display in all DEs and file managers
echo "-> Installing application icon..."
mkdir -p /usr/share/icons/hicolor/128x128/apps/
if [ -f "$INSTALL_DIR/$ICON_SRC" ]; then
    cp "$INSTALL_DIR/$ICON_SRC" "$ICON_DEST"
    chmod 644 "$ICON_DEST"
else
    echo -e "   ${YELLOW}Warning:${NC} Icon file not found, skipping icon installation."
fi

# 11b. File type associations.
#      Policy: AliView must ALWAYS be offered under "Open With" for alignment
#      files, but must NEVER steal an association another application already
#      owns. To honour that:
#        * we install a MIME glob only for an extension that is NOT already
#          mapped to a specific type, so we never change how existing files are
#          classified and never hijack another app's default;
#        * for extensions another app already owns, we add that existing type
#          to our desktop MimeType so we still appear under "Open With";
#        * we never set AliView as the default handler (no `xdg-mime default`,
#          no [Default Applications] entry) — the desktop only makes us default
#          when nothing else claims the type.
echo "-> Configuring file type associations..."

# Remove any MIME package from a previous AliView install first, so the probing
# below reflects only OTHER applications (otherwise a reinstall would see our
# own globs and wrongly treat every extension as already-owned).
if [ -f "$MIME_XML_DEST" ]; then
    rm -f "$MIME_XML_DEST"
    command -v update-mime-database &> /dev/null && \
        update-mime-database /usr/share/mime &> /dev/null || true
fi

# Format family -> extensions and a human-readable comment per family.
FAMILY_ORDER=(application/x-fasta application/x-nexus application/x-phylip application/x-clustal application/x-msf)
declare -A FAMILY_EXTS=(
    [application/x-fasta]="fasta fas fa afa"
    [application/x-nexus]="nexus nex"
    [application/x-phylip]="phylip phy"
    [application/x-clustal]="clustal clustalw clustalx aln"
    [application/x-msf]="msf"
)
declare -A FAMILY_COMMENT=(
    [application/x-fasta]="FASTA sequence alignment"
    [application/x-nexus]="NEXUS alignment"
    [application/x-phylip]="PHYLIP alignment"
    [application/x-clustal]="Clustal alignment"
    [application/x-msf]="MSF alignment"
)

# Return the current specific MIME type for a file extension, or empty if the
# system has no specific mapping (unknown / plain text / generic binary).
current_type_for_ext() {
    local ext="$1" probe t
    command -v xdg-mime &> /dev/null || { echo ""; return; }
    probe="$(mktemp --suffix=".$ext" 2>/dev/null)" || { echo ""; return; }
    printf 'x' > "$probe"
    t="$(xdg-mime query filetype "$probe" 2>/dev/null || true)"
    rm -f "$probe"
    case "$t" in
        ""|text/plain|application/octet-stream|application/x-zerosize|inode/*) echo "" ;;
        *) echo "$t" ;;
    esac
}

MIME_XML_BODY=""
declare -A DESKTOP_TYPES=()   # types to advertise in the desktop MimeType line

for TYPE in "${FAMILY_ORDER[@]}"; do
    OUR_GLOBS=""
    for ext in ${FAMILY_EXTS[$TYPE]}; do
        existing="$(current_type_for_ext "$ext")"
        if [ -n "$existing" ]; then
            echo "   .$ext already handled as '$existing' — not overriding; adding to Open With"
            DESKTOP_TYPES["$existing"]=1
        else
            OUR_GLOBS+="    <glob pattern=\"*.${ext}\"/>"$'\n'
        fi
    done
    if [ -n "$OUR_GLOBS" ]; then
        MIME_XML_BODY+="  <mime-type type=\"${TYPE}\">"$'\n'
        MIME_XML_BODY+="    <comment>${FAMILY_COMMENT[$TYPE]}</comment>"$'\n'
        MIME_XML_BODY+="    <sub-class-of type=\"text/plain\"/>"$'\n'
        MIME_XML_BODY+="${OUR_GLOBS}"
        MIME_XML_BODY+="  </mime-type>"$'\n'
        DESKTOP_TYPES["$TYPE"]=1
    fi
done

# Install our shared-mime-info package only if we own at least one glob.
if [ -n "$MIME_XML_BODY" ]; then
    echo "-> Installing MIME type definitions for unclaimed extensions..."
    mkdir -p "$(dirname "$MIME_XML_DEST")"
    {
        echo '<?xml version="1.0" encoding="UTF-8"?>'
        echo '<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">'
        printf '%s' "$MIME_XML_BODY"
        echo '</mime-info>'
    } > "$MIME_XML_DEST"
    chmod 644 "$MIME_XML_DEST"
else
    echo "   All alignment extensions are already registered — no MIME package installed."
fi

# Desktop MimeType value: our own types plus any pre-existing ones, sorted for
# stable output (trailing ';' is expected by the desktop entry spec).
MIME_TYPES="$(printf '%s;' $(printf '%s\n' "${!DESKTOP_TYPES[@]}" | sort))"

# 12. Desktop entry
#     Categories: one main category (Science) plus the Biology additional
#     category — validates cleanly and shows once in the menu.
echo "-> Registering desktop menu entry..."
mkdir -p /usr/share/applications
cat <<EOF > "$DESKTOP_FILE"
[Desktop Entry]
Version=1.0
Type=Application
Name=AliView
GenericName=Alignment Viewer
Comment=Fast and lightweight alignment viewer and editor
Exec=$BIN_LINK %f
TryExec=$BIN_LINK
Icon=${ICON_DEST_NAME}
Terminal=false
Categories=Science;Biology;
MimeType=${MIME_TYPES}
Keywords=alignment;biology;bioinformatics;fasta;phylip;clustal;nexus;
StartupWMClass=AliView
StartupNotify=true
EOF
chmod 644 "$DESKTOP_FILE"

# 13. Create uninstaller
echo "-> Generating uninstaller..."
cat <<'UNINSTALL_EOF' > "$INSTALL_DIR/uninstall.sh"
#!/bin/bash
set -euo pipefail

# Match the installer: keep regenerated icon/MIME caches world-readable even if
# this is run under a restrictive umask, otherwise the refresh below would write
# root-only caches and break icon loading desktop-wide (see install.sh).
umask 022

# Hardcoded paths — do not use variables for rm -rf targets without a sanity check
INSTALL_DIR="/opt/aliview"
INSTALL_DIR_EXPECTED="/opt/aliview"
BIN_LINK="/usr/local/bin/aliview"
DESKTOP_FILE="/usr/share/applications/aliview.desktop"
ICON_FILE="/usr/share/icons/hicolor/128x128/apps/aliview.png"
MIME_XML="/usr/share/mime/packages/aliview.xml"

if [ "$EUID" -ne 0 ]; then
    echo "Please run with sudo: sudo /opt/aliview/uninstall.sh"
    exit 1
fi

# Sanity check before rm -rf
if [ "$INSTALL_DIR" != "$INSTALL_DIR_EXPECTED" ]; then
    echo "Error: INSTALL_DIR sanity check failed. Aborting to prevent data loss."
    echo "  Expected: $INSTALL_DIR_EXPECTED"
    echo "  Got:      $INSTALL_DIR"
    exit 1
fi

echo "Removing AliView..."
rm -f "$BIN_LINK"
rm -f "$DESKTOP_FILE"
rm -f "$ICON_FILE"
rm -f "$MIME_XML"

# Refresh databases BEFORE rm -rf INSTALL_DIR — do all meaningful work first.
# bash reads the whole script into memory so rm -rf won't cut execution short,
# but this ordering is still correct practice.
echo "-> Refreshing system databases..."
update-desktop-database /usr/share/applications > /dev/null 2>&1 || true
update-mime-database /usr/share/mime > /dev/null 2>&1 || true

# Icon cache — GTK desktops (GNOME, Xfce, LXDE, Cinnamon)
if command -v gtk-update-icon-cache &> /dev/null; then
    gtk-update-icon-cache /usr/share/icons/hicolor/ -f -t > /dev/null 2>&1 || true
fi
# (No kbuildsycoca: KDE rebuilds its per-user sycoca automatically when
#  /usr/share/applications changes; running it as root only rebuilds root's.)

# Final act — remove the install directory (also removes this running script)
rm -rf "$INSTALL_DIR"

echo "AliView has been successfully removed."
UNINSTALL_EOF
chmod 755 "$INSTALL_DIR/uninstall.sh"

# 14. Remove in-progress marker — installation succeeded
rm -f "$INSTALL_MARKER"

# 15. Refresh system databases
echo "-> Refreshing system databases..."
update-desktop-database /usr/share/applications > /dev/null 2>&1 || true
update-mime-database /usr/share/mime > /dev/null 2>&1 || true

# Icon cache — GTK desktops (GNOME, Xfce, LXDE, Cinnamon)
if command -v gtk-update-icon-cache &> /dev/null; then
    gtk-update-icon-cache /usr/share/icons/hicolor/ -f -t > /dev/null 2>&1 || true
fi
# (No kbuildsycoca: KDE rebuilds its per-user sycoca automatically when
#  /usr/share/applications changes; running it as root only rebuilds root's.)

echo ""
echo -e "${GREEN}=== Installation Complete! ===${NC}"
echo "Launch AliView from your Applications menu or by typing 'aliview' in a terminal."
echo "To uninstall, run: sudo $INSTALL_DIR/uninstall.sh"
echo "Install log:       $LOG_FILE"
